export interface KnowledgeTopicPreset {
  id: string;
  topic: string;
  category: 'corporate' | 'legal' | 'trend' | 'marketing' | 'other';
  categoryName: string;
  description: string;
  tag: string;
  badge: '추천' | '필수' | '인기' | '최신';
  recommendedType: 'knowledge' | 'fact';
}

export const KNOWLEDGE_TOPIC_PRESETS: KnowledgeTopicPreset[] = [
  // 1. 기업 규정 / 정관 (Corporate)
  {
    id: 'corp-1',
    topic: '스타트업 주주간계약서(SHA) 및 경영참여·우선매수권 표준 규정',
    category: 'corporate',
    categoryName: '기업 규정 / 정관',
    description: '공동창업자 지분 락업(Lock-up), 동반매도참여권(Tag-along), 의결권 행사 및 지분 처분 제한 표준 조항',
    tag: '#투자유치',
    badge: '필수',
    recommendedType: 'knowledge',
  },
  {
    id: 'corp-2',
    topic: '임직원 스톡옵션(주식매수선택권) 표준 부여 규정 및 계약서',
    category: 'corporate',
    categoryName: '기업 규정 / 정관',
    description: '행사가격 산정 기준, 베스팅(Vesting) 조건, 퇴사 시 권리 행사 및 취소 요건을 완비한 실무 규정',
    tag: '#인재영입',
    badge: '추천',
    recommendedType: 'knowledge',
  },
  {
    id: 'corp-3',
    topic: '사내 취업규칙 및 직장 내 괴롭힘·성희롱 예방 조치 가이드라인',
    category: 'corporate',
    categoryName: '기업 규정 / 정관',
    description: '고용노동부 최신 표준 근로기준법 반영, 징계 절차 및 피해자 보호 조치 체계 규정안',
    tag: '#인사노무',
    badge: '필수',
    recommendedType: 'knowledge',
  },
  {
    id: 'corp-4',
    topic: '회사 상벌 및 징계위원회 운영 규정안',
    category: 'corporate',
    categoryName: '기업 규정 / 정관',
    description: '포상 기준, 징계 사유(견책/감봉/정직/해고) 및 소명 기회 보장과 위원회 의결 절차',
    tag: '#사내규정',
    badge: '인기',
    recommendedType: 'knowledge',
  },
  {
    id: 'corp-5',
    topic: '재택·하이브리드 원격근무 운영 규정 및 보안 서약서',
    category: 'corporate',
    categoryName: '기업 규정 / 정관',
    description: '근무 시간 관리, 근태 기준, 통신비 지원 및 사외 정보보안 준수 수칙',
    tag: '#스마트워크',
    badge: '최신',
    recommendedType: 'knowledge',
  },
  {
    id: 'corp-6',
    topic: '임원 퇴직금 지급 규정 및 주총 결의 표준 정관 부칙',
    category: 'corporate',
    categoryName: '기업 규정 / 정관',
    description: '세법상 인정되는 임원 퇴직소득 배수 기준 및 이사회/주총 결의 절차',
    tag: '#세무법무',
    badge: '추천',
    recommendedType: 'knowledge',
  },

  // 2. 법률 / 계약서 (Legal)
  {
    id: 'legal-1',
    topic: '소프트웨어(SW) 및 AI 솔루션 외주 개발 표준 용역계약서 (SLA 포함)',
    category: 'legal',
    categoryName: '법률 / 계약서',
    description: '지식재산권 귀속, 검수 기준, 하자보수 기간, 소스코드 납품 및 서비스 레벨 협약(SLA)',
    tag: '#IT용역',
    badge: '필수',
    recommendedType: 'knowledge',
  },
  {
    id: 'legal-2',
    topic: '상호 비밀유지협약서 (NDA - Non-Disclosure Agreement) 표준안',
    category: 'legal',
    categoryName: '법률 / 계약서',
    description: '영업비밀 정의, 비밀유지 의무 기간, 위약벌(손해배상 예정액) 산정 및 예외 조항 완비',
    tag: '#기술보호',
    badge: '필수',
    recommendedType: 'knowledge',
  },
  {
    id: 'legal-3',
    topic: '공동사업 추진 및 전략적 업무제휴(MOU / LOI) 표준 협약서',
    category: 'legal',
    categoryName: '법률 / 계약서',
    description: '역할 분담, 비용 정산, 법적 구속력 유무 명시 및 본계약 체결 확약 조항',
    tag: '#전략제휴',
    badge: '인기',
    recommendedType: 'knowledge',
  },
  {
    id: 'legal-4',
    topic: '개인정보 처리방침 및 제3자 제공·위탁 표준 동의서 (개인정보보호법 개정안 반영)',
    category: 'legal',
    categoryName: '법률 / 계약서',
    description: '필수 수집 항목, 보유 및 이용 기간, 파기 절차, 개인정보 보호책임자 지정 표준 양식',
    tag: '#컴플라이언스',
    badge: '필수',
    recommendedType: 'knowledge',
  },
  {
    id: 'legal-5',
    topic: '전문 프리랜서 및 경영 자문 용역 계약서 (3.3% 원천징수)',
    category: 'legal',
    categoryName: '법률 / 계약서',
    description: '근로자성 오인 방지 독립사업자 요건, 결과물 납품 기한 및 자문료 정산 조건',
    tag: '#자문계약',
    badge: '추천',
    recommendedType: 'knowledge',
  },
  {
    id: 'legal-6',
    topic: '독점 판권 공급 및 유통 대리점 계약서 (Distributorship Agreement)',
    category: 'legal',
    categoryName: '법률 / 계약서',
    description: '최소 주문 수량(MOQ), 공급 단가 산정, 독점권 유지 조건 및 계약 해지 사유',
    tag: '#유통영업',
    badge: '최신',
    recommendedType: 'knowledge',
  },

  // 3. 시장 트렌드 / 분석 (Trend)
  {
    id: 'trend-1',
    topic: '2026 국내외 온디바이스 AI 및 생성형 AI 엔터프라이즈 도입 동향과 시장 전망',
    category: 'trend',
    categoryName: '시장 트렌드 / 분석',
    description: '기업용 AI 도입률, LLM 인프라 투자 규모, 글로벌 빅테크 동향 및 정량적 시장 성장률 분석',
    tag: '#생성형AI',
    badge: '인기',
    recommendedType: 'fact',
  },
  {
    id: 'trend-2',
    topic: '2026 K-뷰티 및 K-푸드 글로벌 수출(북미/중동) 동향 및 FDA 규제 대응 전략',
    category: 'trend',
    categoryName: '시장 트렌드 / 분석',
    description: '국가별 수출 통계 추이, 인허가 규정 변경점, 이커머스 D2C 유통 채널 성공 사례',
    tag: '#글로벌수출',
    badge: '추천',
    recommendedType: 'fact',
  },
  {
    id: 'trend-3',
    topic: '2026 대한민국 벤처투자(VC) 펀딩 동향 및 TIPS/정부 R&D 지원사업 선정 가이드',
    category: 'trend',
    categoryName: '시장 트렌드 / 분석',
    description: '초기 스타트업 투자 금액 통계, 딥테크 팁스 심사 주안점, 모태펀드 출자 방향성',
    tag: '#투자유치',
    badge: '필수',
    recommendedType: 'fact',
  },
  {
    id: 'trend-4',
    topic: '국내 차세대 2차전지 및 폐배터리 리사이클링 산업 밸류체인 분석',
    category: 'trend',
    categoryName: '시장 트렌드 / 분석',
    description: 'EU 배터리 여권 규제 영향, 국내 주요 재활용 기업 설비 투자 및 원자재 회수율 지표',
    tag: '#클린테크',
    badge: '최신',
    recommendedType: 'fact',
  },
  {
    id: 'trend-5',
    topic: 'B2B SaaS 기업의 AI 전환(AX) 성공 사례 및 ARR/NDR 벤치마크 지표',
    category: 'trend',
    categoryName: '시장 트렌드 / 분석',
    description: '순수익 유지율(NDR), 고객획득비용(CAC) 회수 기간 및 AI 기능 탑재에 따른 ARPU 상승치',
    tag: '#B2BSaaS',
    badge: '추천',
    recommendedType: 'fact',
  },

  // 4. 마케팅 / 브랜드 (Marketing)
  {
    id: 'mkt-1',
    topic: '글로벌 숏폼(틱톡·릴스·쇼츠) 인플루언서 마케팅 표준 가이드라인 및 성과 측정 지표',
    category: 'marketing',
    categoryName: '마케팅 / 브랜드',
    description: '광고 표기법 준수, 크리에이터 계약 조건, 바이럴 ROAS 및 전환율(CVR) 산정 매뉴얼',
    tag: '#숏폼바이럴',
    badge: '인기',
    recommendedType: 'knowledge',
  },
  {
    id: 'mkt-2',
    topic: '초개인화 CRM 마케팅 자동화 시나리오 및 고객 생애가치(LTV) 극대화 전략',
    category: 'marketing',
    categoryName: '마케팅 / 브랜드',
    description: '첫 구매 유도, 이탈 방지 트리거 메시지 설계, 코호트 분석 및 RFM 세그먼트 구축',
    tag: '#CRM자동화',
    badge: '필수',
    recommendedType: 'knowledge',
  },
  {
    id: 'mkt-3',
    topic: '신규 브랜드 런칭 시 브랜드 아이덴티티(BI) 가이드라인 및 톤앤매너 매뉴얼',
    category: 'marketing',
    categoryName: '마케팅 / 브랜드',
    description: '브랜드 핵심 가치(Core Value), 슬로건, 비주얼 시스템 규정 및 고객 커뮤니케이션 원칙',
    tag: '#브랜딩',
    badge: '추천',
    recommendedType: 'knowledge',
  },
  {
    id: 'mkt-4',
    topic: 'B2B 테크 기업 리드 제너레이션 및 웨비나 전환 퍼널 구축 가이드',
    category: 'marketing',
    categoryName: '마케팅 / 브랜드',
    description: 'MQL에서 SQL로의 리드 스코어링 체계, 백서(Whitepaper) 다운로드 퍼널 및 콜드메일 전략',
    tag: '#B2B마케팅',
    badge: '최신',
    recommendedType: 'knowledge',
  },
  {
    id: 'mkt-5',
    topic: '퍼포먼스 마케팅 소재 A/B 테스트 매뉴얼 및 ROAS 최적화 체크리스트',
    category: 'marketing',
    categoryName: '마케팅 / 브랜드',
    description: '메타·구글·네이버 광고 매체별 소재 피로도 관리, 후킹 포인트 분석 및 랜딩페이지 최적화',
    tag: '#퍼포먼스',
    badge: '추천',
    recommendedType: 'knowledge',
  },

  // 5. 기타 / 비즈니스 (Other)
  {
    id: 'other-1',
    topic: '사내 생성형 AI(LLM) 도입 보안 수칙 및 사내 데이터 유출 방지(DLP) 가이드라인',
    category: 'other',
    categoryName: '기타 비즈니스',
    description: '기밀 데이터 프롬프트 입력 금지 규정, 저작권 분쟁 예방, AI 산출물 검증 프로세스',
    tag: '#AI보안',
    badge: '필수',
    recommendedType: 'knowledge',
  },
  {
    id: 'other-2',
    topic: 'OKR 기반 전사 목표 수립 및 분기별 CFR(대화·피드백·인정) 운영 매뉴얼',
    category: 'other',
    categoryName: '기타 비즈니스',
    description: 'Objective와 Key Result 작성 공식, 1on1 미팅 가이드라인 및 성과 피드백 체크리스트',
    tag: '#성과관리',
    badge: '추천',
    recommendedType: 'knowledge',
  },
  {
    id: 'other-3',
    topic: '클라우드(AWS/GCP) 인프라 보안 및 재해복구(DR) 표준 운영 매뉴얼',
    category: 'other',
    categoryName: '기타 비즈니스',
    description: 'RTO(복구목표시간) / RPO(복구시점목표) 수립, 정기 백업 및 IAM 계정 권한 분리 규정',
    tag: '#인프라보안',
    badge: '필수',
    recommendedType: 'knowledge',
  },
  {
    id: 'other-4',
    topic: '신규 입사자 온보딩(Onboarding) 웰컴 프로세스 및 30-60-90일 안착 플랜',
    category: 'other',
    categoryName: '기타 비즈니스',
    description: '버디 프로그램 운영, 필수 교육 이수 목록, 수습 평가 기준 및 웰컴킷 구성 가이드',
    tag: '#조직문화',
    badge: '인기',
    recommendedType: 'knowledge',
  },
  {
    id: 'other-5',
    topic: 'ISO 27001 정보보안 경영시스템 인증 취득을 위한 사내 자가진단 체크리스트',
    category: 'other',
    categoryName: '기타 비즈니스',
    description: '물리적/관리적/기술적 보안 통제 93개 항목별 준수 확인 및 증빙 자료 준비 가이드',
    tag: '#ISO인증',
    badge: '최신',
    recommendedType: 'knowledge',
  },
];
