import { PresentationThemeId, ThemeConfig, PresentationPreset } from '../types/presentation';

export const PRESENTATION_THEMES: Record<PresentationThemeId, ThemeConfig> = {
  dark_navy: {
    id: 'dark_navy',
    name: '인베스터 다크 네이비',
    description: 'VC 투자 유치 및 IR 피치덱에 최적화된 신뢰감 있는 딥 네이비 & 골드 테마',
    bgClass: 'bg-slate-950 text-slate-100',
    cardBgClass: 'bg-slate-900/90 border border-slate-800',
    textPrimary: 'text-white',
    textSecondary: 'text-slate-400',
    accentClass: 'text-amber-400',
    accentBadge: 'bg-amber-400/10 text-amber-300 border-amber-400/20',
    borderClass: 'border-slate-800',
    pptxColors: {
      bg: '0F172A',
      cardBg: '1E293B',
      titleColor: 'FFFFFF',
      bodyColor: 'CBD5E1',
      accentColor: 'F59E0B',
      secondaryAccent: '38BDF8',
      border: '334155',
    },
  },
  tech_indigo: {
    id: 'tech_indigo',
    name: '모던 테크 인디고',
    description: 'IT/소프트웨어, AI/데이터, SaaS 제안서에 최적화된 모던하고 세련된 테마',
    bgClass: 'bg-slate-900 text-slate-100',
    cardBgClass: 'bg-slate-800/90 border border-slate-700/80',
    textPrimary: 'text-white',
    textSecondary: 'text-slate-300',
    accentClass: 'text-indigo-400',
    accentBadge: 'bg-indigo-500/15 text-indigo-300 border-indigo-500/30',
    borderClass: 'border-slate-700',
    pptxColors: {
      bg: '1E1B4B',
      cardBg: '312E81',
      titleColor: 'FFFFFF',
      bodyColor: 'E0E7FF',
      accentColor: '6366F1',
      secondaryAccent: '818CF8',
      border: '4338CA',
    },
  },
  emerald_growth: {
    id: 'emerald_growth',
    name: '에메랄드 그로스',
    description: '바이오, 헬스케어, ESG, 친환경, 교육 분야에 적합한 신선하고 지속가능한 테마',
    bgClass: 'bg-[#062419] text-emerald-50',
    cardBgClass: 'bg-[#0c3828] border border-emerald-800/60',
    textPrimary: 'text-white',
    textSecondary: 'text-emerald-200/70',
    accentClass: 'text-emerald-400',
    accentBadge: 'bg-emerald-400/15 text-emerald-300 border-emerald-400/30',
    borderClass: 'border-emerald-800/80',
    pptxColors: {
      bg: '062419',
      cardBg: '0C3828',
      titleColor: 'FFFFFF',
      bodyColor: 'D1FAE5',
      accentColor: '10B981',
      secondaryAccent: '34D399',
      border: '065F46',
    },
  },
  creative_coral: {
    id: 'creative_coral',
    name: '크리에이티브 코랄',
    description: '마케팅, 광고/PR, 엔터테인먼트, 런칭 제안에 어울리는 생동감 넘치는 테마',
    bgClass: 'bg-[#181124] text-rose-50',
    cardBgClass: 'bg-[#291d3d] border border-purple-800/60',
    textPrimary: 'text-white',
    textSecondary: 'text-rose-200/70',
    accentClass: 'text-rose-400',
    accentBadge: 'bg-rose-500/15 text-rose-300 border-rose-500/30',
    borderClass: 'border-purple-800/80',
    pptxColors: {
      bg: '181124',
      cardBg: '291D3D',
      titleColor: 'FFFFFF',
      bodyColor: 'FFE4E6',
      accentColor: 'F43F5E',
      secondaryAccent: 'C084FC',
      border: '6B21A8',
    },
  },
  clean_slate: {
    id: 'clean_slate',
    name: '클린 라이트 미니멀',
    description: '공공기관, 연구보고서, 학술 발표에 적합한 깔끔하고 인쇄 친화적인 밝은 테마',
    bgClass: 'bg-slate-50 text-slate-900',
    cardBgClass: 'bg-white border border-slate-200 shadow-xs',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    accentClass: 'text-indigo-600',
    accentBadge: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    borderClass: 'border-slate-200',
    pptxColors: {
      bg: 'F8FAFC',
      cardBg: 'FFFFFF',
      titleColor: '0F172A',
      bodyColor: '334155',
      accentColor: '4F46E5',
      secondaryAccent: '2563EB',
      border: 'E2E8F0',
    },
  },
};

export const PRESENTATION_PRESETS: PresentationPreset[] = [
  {
    id: 'ir_pitch_seed',
    name: '스타트업 시드/프리A IR 피치덱 (10장)',
    description: '문제정의부터 솔루션, 시장규모, 비즈니스 모델, 트랙션 및 투자 유치(Ask)까지 완벽 구성',
    field: 'management',
    presentationType: 'ir_pitch',
    theme: 'dark_navy',
    iconName: 'TrendingUp',
    defaultData: {
      field: 'management',
      presentationType: 'ir_pitch',
      theme: 'dark_navy',
      topic: 'AI 기반 B2B 업무 자동화 SaaS 플랫폼 투자 유치 피치덱',
      purpose: '벤처캐피탈(VC) 및 엔젤투자자 대상 15억 원 규모 Pre-A 라운드 투자 유치',
      targetAudience: '초기 스타트업 전문 VC 심사역 및 파트너',
      companyName: '(주)넥스트오토메이트',
      slideCountPreference: 10,
      keyPoints: 'LLM 기반 복합 워크플로우 자동화, 출시 6개월 만에 유료 기업 고객 120개사 확보, MoM 35% 성장, TAM 12조 원 시장',
    },
  },
  {
    id: 'b2b_si_proposal',
    name: 'B2B 엔터프라이즈 DX 수주 제안서 (12장)',
    description: '고객사 Pain Point 분석, To-Be 아키텍처, 수행 체계, WBS 일정 및 기대효과 ROI 도출',
    field: 'it_tech',
    presentationType: 'b2b_proposal',
    theme: 'tech_indigo',
    iconName: 'Laptop',
    defaultData: {
      field: 'it_tech',
      presentationType: 'b2b_proposal',
      theme: 'tech_indigo',
      topic: '금융사 차세대 클라우드 데이터 파이프라인 및 실시간 이상거래 탐지(FDS) 구축 제안',
      purpose: '시중은행 디지털혁신본부 대상 25억 규모 차세대 DX 사업 우선협상대상자 선정',
      targetAudience: '금융사 CIO, IT 기획부서장 및 보안 총괄 임원',
      companyName: '클라우드웨이브 테크놀로지',
      slideCountPreference: 12,
      keyPoints: '초당 10만 건 분산 처리 아키텍처, 99.999% 무중단 가용성, 금융보안원 규정 100% 준수, 평균 탐지 지연시간 20ms 이하',
    },
  },
  {
    id: 'marketing_growth_deck',
    name: '신제품 D2C 런칭 & 통합 마케팅 전략 (10장)',
    description: '타겟 페르소나 분석, 4P 믹스, 퍼포먼스 마케팅 퍼널, 인플루언서 캠페인 및 예산/KPI',
    field: 'marketing',
    presentationType: 'marketing_deck',
    theme: 'creative_coral',
    iconName: 'Megaphone',
    defaultData: {
      field: 'marketing',
      presentationType: 'marketing_deck',
      theme: 'creative_coral',
      topic: 'MZ세대 타겟 친환경 웰니스 비건 스킨케어 브랜드 런칭 마케팅 전략',
      purpose: '신규 브랜드 출시 후 3개월 내 브랜드 인지도 40% 달성 및 D2C 자사몰 매출 10억 돌파',
      targetAudience: '경영진 및 마케팅 본부장, 총괄 디렉터',
      companyName: '비건글로우 코스메틱스',
      slideCountPreference: 10,
      keyPoints: '클린뷰티 버티컬 타겟팅, 숏폼 바이럴 챌린지, 성수동 팝업스토어 OMO 연계, CAC 절감 및 ROAS 380% 목표',
    },
  },
  {
    id: 'new_biz_plan',
    name: '신사업 추진 계획서 & 사업성 분석 (10장)',
    description: '신시장 기회 요인, 3C 분석, 핵심 역량 매핑, 3개년 재무 추정 및 마일스톤',
    field: 'planning',
    presentationType: 'business_plan',
    theme: 'emerald_growth',
    iconName: 'Compass',
    defaultData: {
      field: 'planning',
      presentationType: 'business_plan',
      theme: 'emerald_growth',
      topic: '도심형 스마트 모빌리티 배터리 구독 및 교환 스테이션(BSS) 신사업 추진 계획',
      purpose: '이사회 및 투자심의위원회 신사업 승인 및 1단계 인프라 투자 예산 30억 확보',
      targetAudience: '대표이사, 사외이사 및 투자심의위원',
      companyName: '에코파워 모빌리티',
      slideCountPreference: 10,
      keyPoints: '도심 거점 50개소 우선 구축, 1분 퀵 배터리 교환, 구독형 MRR 수익 모델, 2년 차 손익분기점(BEP) 달성',
    },
  },
];
